smart (sh) smart.conf

diff --git a/etc/cron.daily/smart b/etc/cron.daily/smart
--- a/etc/cron.daily/smart
+++ b/etc/cron.daily/smart
@@ -1,31 +1,33 @@
 #!/bin/bash
 # v3 smartctl disk check
 # v4 set RAID in .conf
+# v5 adjust use of smartctl
 Name=$( basename $0 )
-if [[ -r $Name.conf ]]; then source $Name.conf; else echo $Name: missing .conf; exit 1; fi
+if [[ -r $Name.conf ]]; then . $Name.conf; else echo no $Name.conf; exit 1; fi
 
 # smartctl -A -d sat+megaraid,12 /dev/sda
 # smartctl -A -d 3ware,1 /dev/twa0 # 9650 
 # smartctl -A -d 3ware,1 /dev/twl0 # 9750 
 
 # reporting
-# 5 Reallocated_Sector_Ct, 9 Power_On_Hours, 10 Spin_Retry_Count,
-# 197 Current_Pending_Sector, 198 Offline_Uncorrectable
+# 5 Reallocated_Sector_Ct   0x0033   001   001   005    Pre-fail  Always   FAILING_NOW 1990
 awkS='
-/^  5 /{if ($10 > 0) printf "%d = %s ", $10, $2 }
-/^ 10 /{if ($10 > 0) printf "%d = %s ", $10, $2 }
-/^194 /{if ($10 > 36) printf "%d = %s ", $10, $2 }
-/^197 /{if ($10 > 0) printf "%d = %s ", $10, $2 }
-/^198 /{if ($10 > 0) printf "%d = %s ", $10, $2 }
+/^  5 /{if ($10 > 0) printf " %d %s %s ", $10, $9, $2 }
+/^ 10 /{if ($10 > 0) printf " %d %s %s ", $10, $9, $2 }
+/^194 /{if ($10 > 36) printf " %d %s %s ", $10, $9, $2 }
+/^197 /{if ($10 > 0) printf " %d %s %s ", $10, $9, $2 }
+/^198 /{if ($10 > 0) printf " %d %s %s ", $10, $9, $2 }
 /^  9 /{x=$10/24/365; if (x > 4) printf "(%1.1f years) ", x }
 '
+#awkS='/^  5 /{printf "%d = %s ", $10, $2 }'
 
 # quickie
 if [[ -n "$1" ]]; then
   echo "== $1"
+  awkS='/^  5 /{printf "%d = %s ", $10, $2 }'
   out=$( smartctl -d sat -A $1 | awk "$awkS" )
   if [[ -n $out ]]; then
-    echo "$out SATA disk $1"
+    echo "disk $1 SATA $out"
   fi
   exit
 fi
@@ -36,26 +38,35 @@ fi
 # could use lsblk
 
 # SATA or PATA
-Sata=$( smartctl --scan-open | awk '/sat/{print $1}')
+Sata=$( smartctl --scan-open | awk '/ sat /{print $1}')
 
 # hello
 echo == smart: looking for sector errs on $( hostname )
 if [[ -n "$Sata" ]]; then echo SATA $Sata; fi
-if [[ -n "$Rtype" ]]; then echo RAID $Rtype $Rdev; fi
 
 ## non-raid
 for i in $Sata; do
   out=$( smartctl -d sat -A $i | awk "$awkS" )
   if [[ -n $out ]]; then
-    echo "$out SATA disk $i"
+    echo "disk $i SATA $out"
   fi
 done
 
 ## raid
-for (( j=0; j<30; j++ )); do
+if [[ -n "$Rtype" ]]; then echo RAID $Rtype $Rdev; fi
+for (( j=0; j<32; j++ )); do
   out=$( smartctl -d $Rtype,$j -A $Rdev | awk "$awkS" )
   if [[ -n "$out" ]]; then
-    echo "$out on disk $Rtype,$j $Rdev"
+    echo "disk $j $out"
+  fi
+done
+
+## raid2
+if [[ -n "$Rtype2" ]]; then echo RAID $Rtype2 $Rdev2; fi
+for (( j=0; j<32; j++ )); do
+  out=$( smartctl -d $Rtype2,$j -A $Rdev2 | awk "$awkS" )
+  if [[ -n "$out" ]]; then
+    echo "disk $j $out"
   fi
 done
 
